-- feito por: Livia

-- tabela usuarios
CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(150 BYTE) NOT NULL,
    email VARCHAR2(255 BYTE) NOT NULL,
    telefone VARCHAR2(20 BYTE),
    senha VARCHAR2(255 BYTE) NOT NULL,
    criado_em TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    tem_instituicao NUMBER(1,0) DEFAULT 0,
    tem_cursos NUMBER(1,0) DEFAULT 0,
    primeiro_acesso NUMBER(1,0) DEFAULT 1
);

ALTER TABLE usuarios ADD CONSTRAINT uk_usuarios_email UNIQUE (email);

-- tabela instituições
CREATE TABLE instituicoes (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL,
    nome VARCHAR2(255 BYTE) NOT NULL,
    criado_em TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    sigla VARCHAR2(20 BYTE),

    CONSTRAINT fk_inst_usuario
      FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

-- tabela cursos
CREATE TABLE cursos (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    instituicao_id NUMBER NOT NULL,
    usuario_id NUMBER NOT NULL,
    nome VARCHAR2(255 BYTE) NOT NULL,
    criado_em TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    sigla VARCHAR2(20 BYTE),
    coordenador VARCHAR2(255 BYTE),

    CONSTRAINT fk_cursos_inst FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id),
    CONSTRAINT fk_cursos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

-- tabela disciplinas
CREATE TABLE disciplinas (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    curso_id NUMBER NOT NULL,
    usuario_id NUMBER NOT NULL,
    nome VARCHAR2(255 BYTE) NOT NULL,
    sigla VARCHAR2(20 BYTE) NOT NULL,
    codigo VARCHAR2(50 BYTE) NOT NULL,
    periodo VARCHAR2(50 BYTE),
    criado_em TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    instituicao_id NUMBER NOT NULL,

    CONSTRAINT fk_disc_curso FOREIGN KEY (curso_id) REFERENCES cursos(id),
    CONSTRAINT fk_disc_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_disc_inst FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id)
);

-- tabela turmas
CREATE TABLE turmas (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    instituicao_id NUMBER NOT NULL,
    curso_id NUMBER NOT NULL,
    disciplina_id NUMBER NOT NULL,
    nome VARCHAR2(100 BYTE) NOT NULL,
    dia_semana VARCHAR2(20 BYTE),
    horario VARCHAR2(20 BYTE),
    local_turma VARCHAR2(100 BYTE),
    criado_em TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_turmas_inst FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id),
    CONSTRAINT fk_turmas_curso FOREIGN KEY (curso_id) REFERENCES cursos(id),
    CONSTRAINT fk_turmas_disc FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id)
);

-- tabela alunos
CREATE TABLE alunos (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    matricula VARCHAR2(20 BYTE) NOT NULL,
    nome VARCHAR2(150 BYTE) NOT NULL,
    criado_em TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    instituicao_id NUMBER,
    curso_id NUMBER,
    disciplina_id NUMBER,
    turma_id NUMBER,

    CONSTRAINT fk_aluno_inst FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id),
    CONSTRAINT fk_aluno_curso FOREIGN KEY (curso_id) REFERENCES cursos(id),
    CONSTRAINT fk_aluno_disc FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id),
    CONSTRAINT fk_aluno_turma FOREIGN KEY (turma_id) REFERENCES turmas(id)
);

-- tabela componente de nota
CREATE TABLE componentes_nota (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    disciplina_id NUMBER NOT NULL,
    nome VARCHAR2(255 BYTE) NOT NULL,
    sigla VARCHAR2(20 BYTE) NOT NULL,
    peso NUMBER(5,2),
    descricao VARCHAR2(500 BYTE),
    usuario_id NUMBER NOT NULL,
    tipo_media VARCHAR2(20 BYTE),
    criado_em TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_comp_disc FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id),
    CONSTRAINT fk_comp_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

-- tabela notas
CREATE TABLE notas (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    turma_id NUMBER NOT NULL,
    aluno_id NUMBER NOT NULL,
    componente_id NUMBER NOT NULL,
    valor NUMBER(5,2),

    CONSTRAINT fk_notas_turma FOREIGN KEY (turma_id) REFERENCES turmas(id),
    CONSTRAINT fk_notas_aluno FOREIGN KEY (aluno_id) REFERENCES alunos(id),
    CONSTRAINT fk_notas_comp FOREIGN KEY (componente_id) REFERENCES componentes_nota(id)
);

-- auditoria
CREATE TABLE auditoria_notas (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,

    aluno_id        NUMBER NOT NULL,
    turma_id        NUMBER NOT NULL,
    componente_id   NUMBER NOT NULL,

    valor_antigo    NUMBER(5,2),
    valor_novo      NUMBER(5,2) NOT NULL,

    data_operacao   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    mensagem        VARCHAR2(1000)
);

CREATE OR REPLACE TRIGGER tg_auditoria_notas
AFTER INSERT OR UPDATE ON notas
FOR EACH ROW
DECLARE
    v_msg VARCHAR2(1000);
BEGIN
    v_msg :=
        'Aluno ID ' || :NEW.aluno_id ||
        ' | Turma ID ' || :NEW.turma_id ||
        ' | Componente ID ' || :NEW.componente_id ||
        ' | Nota de ' || NVL(:OLD.valor, 0) ||
        ' para ' || :NEW.valor;

    INSERT INTO auditoria_notas (
        aluno_id,
        turma_id,
        componente_id,
        valor_antigo,
        valor_novo,
        mensagem
    ) VALUES (
        :NEW.aluno_id,
        :NEW.turma_id,
        :NEW.componente_id,
        :OLD.valor,
        :NEW.valor,
        v_msg
    );
END;
/

